swagger: "2.0"
info:
  version: "0.0.1"
  title: Work Planner
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /libs/{folder}/{name}:
    x-swagger-router-controller: libs
    get:
      operationId: fileserve
      description: return selected files
      parameters:
        - name: folder
          type: string
          in: path
          required: true
        - name: name
          type: string
          in: path
          required: true
      produces:
        - text/html; charset=utf-8
        - text/css
        - text/javascript
      responses:
        200:
          description: Success
          schema:
            type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /home:
    x-swagger-router-controller: web_controller
    get:
      operationId: homepage
      description: Returns homepage
      produces:
        - text/html; charset=utf-8
      responses:
        200:
          description: Success
          schema:
            type: string
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project:
    x-swagger-router-controller: management_controller
    get:
      description: Shows list of projects
      operationId: getProjects
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AllProjectsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Creates new project
      operationId: createProject
      parameters:
        - name: title
          in: formData
          description: Project title
          required: true
          type: string
        - name: description
          description: Project description
          in: formData
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ProjectResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/{id}:
    x-swagger-router-controller: management_controller
    get:
      description: Shows a project
      operationId: getProject
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ProjectResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Creates new directory for project
      operationId: createDirectory
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
        - name: title
          in: formData
          description: Directory title
          required: true
          type: string
        - name: description
          in: formData
          description: Directory description
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DirectoryResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Modifies a project
      operationId: modifyProject
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
        - name: title
          in: formData
          description: Project title
          type: string
        - name: description
          description: Project description
          in: formData
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/ProjectResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Deletes a project with all associated items
      operationId: deleteProject
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AllProjectsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/{id}/{directoryId}:
    x-swagger-router-controller: management_controller
    get:
      description: Shows a directory
      operationId: getDirectory
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
        - name: directoryId
          in: path
          description: Directory ID
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DirectoryResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Creates new issue in directory
      operationId: createIssue
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
        - name: directoryId
          in: path
          description: Directory ID
          required: true
          type: string
        - name: title
          in: formData
          description: Title of issue
          required: true
          type: string
        - name: description
          in: formData
          description: Issue description
          type: string
        - name: priority
          in: formData
          description: Issue priority
          type: string
        - name: tag
          in: formData
          description: Issue tag
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/IssueResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Modifies directory
      operationId: modifyDirectory
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
        - name: directoryId
          in: path
          description: Directory ID
          required: true
          type: string
        - name: title
          in: formData
          description: Directory title
          type: string
        - name: description
          in: formData
          description: Directory description
          type: string
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/DirectoryResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
    delete:
      description: Deletes directory
      operationId: deleteDirectory
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
        - name: directoryId
          in: path
          description: Directory ID
          required: true
          type: string
      responses:
          "200":
            description: Success
            schema:
              $ref: "#/definitions/ProjectResponse"
          default:
            description: Error
            schema:
              $ref: "#/definitions/ErrorResponse"
  /project/{id}/{directoryId}/{issueId}:
    x-swagger-router-controller: management_controller
    get:
      description: Shows an issue
      operationId: getIssue
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
        - name: directoryId
          in: path
          description: Directory ID
          required: true
          type: string
        - name: issueId
          in: path
          description: Issue ID
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/IssueResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    post:
      description: Creates new comment in issue
      operationId: createComment
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
        - name: directoryId
          in: path
          description: Directory ID
          required: true
          type: string
        - name: issueId
          in: path
          description: Issue ID
          required: true
          type: string
        - name: content
          in: formData
          description: Comment content
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/IssueResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    put:
      description: Modifies an issue
      operationId: modifyIssue
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
        - name: directoryId
          in: path
          description: Directory ID
          required: true
          type: string
        - name: issueId
          in: path
          description: Issue ID
          required: true
          type: string
        - name: title
          in: formData
          description: Title of issue
          type: string
        - name: description
          in: formData
          description: Issue description
          type: string
        - name: status
          in: formData
          description: Issue status
          type: string
        - name: priority
          in: formData
          description: Issue priority
          type: string
        - name: tag
          in: formData
          description: Issue tag
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/IssueResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Deletes an issue
      operationId: deleteIssue
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
        - name: directoryId
          in: path
          description: Directory ID
          required: true
          type: string
        - name: issueId
          in: path
          description: Issue ID
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/DirectoryResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /project/{id}/{directoryId}/{issueId}/{commentId}:
    x-swagger-router-controller: management_controller
    put:
      description: Modifies a comment
      operationId: modifyComment
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
        - name: directoryId
          in: path
          description: Directory ID
          required: true
          type: string
        - name: issueId
          in: path
          description: Issue ID
          required: true
          type: string
        - name: commentId
          in: path
          description: Comment ID
          required: true
          type: string
        - name: content
          in: formData
          description: Comment content
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/IssueResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      description: Deletes a comment
      operationId: deleteComment
      parameters:
        - name: id
          in: path
          description: Project ID
          required: true
          type: string
        - name: directoryId
          in: path
          description: Directory ID
          required: true
          type: string
        - name: issueId
          in: path
          description: Issue ID
          required: true
          type: string
        - name: commentId
          in: path
          description: Comment ID
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/IssueResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  AllProjectsResponse:
    properties:
      projects:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            title:
              type: string
  ProjectResponse:
    required:
      - id
      - title
    properties:
      id: 
        type: string
      title:
        type: string
      description:
        type: string
      directories:
        type: array
        items:
          type: object
          properties:
            id: 
              type: string
            title:
              type: string
  DirectoryResponse:
    required:
      - id
      - title
      - idProject
    properties:
      id:
        type: string
      title:
        type: string
      description:
        type: string
      idProject:
        type: string
      issues:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            title:
              type: string
            createDate:
              type: string
            modifyDate:
              type: string
            status:
              type: string
            priority:
              type: string
            tag:
              type: string
  IssueResponse:
    required:
      - id
      - title
      - createDate
      - status
      - tag
      - idDirectory
    properties:
      id:
        type: string
      title:
        type: string
      description:
        type: string
      createDate:
        type: string
      modifyDate:
        type: string
      status:
        type: string
      priority:
        type: string
      tag:
        type: string
      idDirectory:
        type: string
      comments:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            createDate:
              type: string
            modifyDate:
              type: string
            content:
              type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
